<?php

namespace App\Exports;

use App\Models\Entry;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;

class EntryExport implements FromCollection, WithHeadings
{
    /**
    * @return \Illuminate\Support\Collection
    */
    public function collection()
    {
        return Entry::all()->map(function ($entry) {
            return $entry->only([
                'project_lac_no',
                'project_description',
                'region',
                'project_phase',
                'proceed',
                'case_file_no',
                'diagram_status',
                'anticipated_date',
                'date_received_via_pims',
                'acquisition_status',
                'acquisition_plan',
                'acquisition_plan_number',
                'spatial_atlas_status',
                'date_of_approval',
                'received_diagram_instruction_via_pims',
                'cancellation_date',
                'cancellation_reason',
                'on_hold_date',
                'on_hold_reason',
                'relocation',
                'linked_to_diagram',
                'valuer',
                'negotiator',
                'contacted_the_owner',
                'site_inspected',
                'staking_requested',
                'issues',
                'pto',
                'type_of_acquisition',
                'signed_agreement',
                'date_owner_signed',
                'date_of_occupation',
                'further_conditions_sent',
                'further_conditions_approved',
                'final_offer_made',
                'date_final_offer_expiring',
                'failed_neg_report_submitted',
                'negotiation_report_submitted',
                'qa_passed',
                'qa_referred_back_to_valuer',
                'date_sent_memo_request',
                'date_memo_uploaded',
                'date_memo_submitted_to_sanral',
                'property_type',
                'portion_number',
                'erf_number',
                'remainder',
                'township',
                'extension',
                'unit_number',
                'scheme_name',
                'scheme_number',
                'portion_of_portion',
                'farm_name',
                'farm_number',
                'portion_number_agricultural',
                'agricultural_holding_name',
                'agricultural_holding_number',
                'remainder_agricultural',
                'site_number',
                'community',
                'chief',
                'erf_number_community',
                'registration_division',
                'acquisition_area_extend',
                'parent_property_area',
                'spatial_atlas',
                'owner_type',
                'owner',
                'pgpw',
                'dpw',
                'dalrrd',
                'transnet'
            ]);
        });
    }


    public function headings(): array
    {
        return [
            'Project LAC No',
            'Project Description',
            'Region',
            'Project Phase',
            'Proceed',
            'Case File No',
            'Diagram Status',
            'Anticipated Date',
            'Date Received via PIMS',
            'Acquisition Status',
            'Acquisition Plan',
            'Acquisition Plan Number',
            'Spatial Atlas Status',
            'Date of Approval',
            'Received Diagram Instruction via PIMS',
            'Cancellation Date',
            'Cancellation Reason',
            'On Hold Date',
            'On Hold Reason',
            'Relocation',
            'Linked to Diagram',
            'Valuer',
            'Negotiator',
            'Contacted the Owner',
            'Site Inspected',
            'Staking Requested',
            'Issues',
            'PTO',
            'Type of Acquisition',
            'Signed Agreement',
            'Date Owner Signed',
            'Date of Occupation',
            'Further Conditions Sent',
            'Further Conditions Approved',
            'Final Offer Made',
            'Date Final Offer Expiring',
            'Failed NEG Report Submitted',
            'Negotiation Report Submitted',
            'QA Passed',
            'QA Referred Back to Valuer',
            'Date Sent Memo Request',
            'Date Memo Uploaded',
            'Date Memo Submitted to SANRAL',
            'Property Type',
            'Portion Number',
            'ERF Number',
            'Remainder',
            'Township',
            'Extension',
            'Unit Number',
            'Scheme Name',
            'Scheme Number',
            'Portion of Portion',
            'Farm Name',
            'Farm Number',
            'Portion Number Agricultural',
            'Agricultural Holding Name',
            'Agricultural Holding Number',
            'Remainder Agricultural',
            'Site Number',
            'Community',
            'Chief',
            'ERF Number Community',
            'Registration Division',
            'Acquisition Area Extend',
            'Parent Property Area',
            'Spatial Atlas',
            'Owner Type',
            'Owner',
            'PGPW',
            'DPW',
            'DALRRD',
            'Transnet'
        ];
    }
}
